{% set name = "pylops" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 966e33dba76d368058c3402b18aaf0b72e183503b46afeb6f8465897f33aafdd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py2k]

requirements:
  build:
      - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - llvmlite
    - numba
    - pyfftw
    - scikit-fmm
    - scipy

test:
  imports:
    - pylops

about:
  home: https://github.com/equinor/pylops
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'PyLops – A Linear-Operator Library for Python'
  description: |
    Python library implementing linear operators to allow solving large-scale optimization
    problems without requiring to explicitly create a dense (or sparse) matrix.
  doc_url: https://pylops.readthedocs.io
  dev_url: https://github.com/equinor/pylops

extra:
  recipe-maintainers:
    - jan-janssen
    - mrava87
